### ISSUE TITLE
is this project alive?

### ISSUE THREAD

**Issue by akhoury** [aws/apprunner-roadmap#212]

**Comment by kachebb** [comment]
I'll borrow this thread to share my similar concern today. 

I'm an independent developer playing with a toy project. Apprunner seems to be what I need, at least based on the documentation and marketing materials. However, I spent almost a few more hours trying to set it up but hardly moved forward. 

1. It tells me service creation and update failed but these are the only log I saw.  What went wrong?
```
09-24-2023 02:08:09 PM [AppRunner] Starting source code build.
09-24-2023 02:08:09 PM [AppRunner] Successfully Validate configuration file.
09-24-2023 02:08:08 PM [AppRunner] Reading apprunner.yaml config file.
09-24-2023 02:07:41 PM [AppRunner] Successfully pulled source code.
09-24-2023 02:07:36 PM [AppRunner] Successfully created pipeline for automatic deployments.
09-24-2023 02:06:55 PM [AppRunner] Service status is set to OPERATION_IN_PROGRESS.
```

2. I don't see the `Go to Environment variables - optional under Service settings` in the AWS Console.  As described in the document. https://docs.aws.amazon.com/apprunner/latest/dg/env-variable-manage.html

3. There is a red banner at top saying web ACL is missing. But my understanding is that it's optional.  Is it required?

**Comment by akhoury** [comment]
I couldn't get a simple nodejs project https://github.com/drschoice/aws-apprunner-demo0 running with the proper ENV VARs during build...

1) if I use `apprunner.yaml`

```
version: 1.0
runtime: nodejs16
build:
  env:
    - name: MYVAR
      value: FOO
  commands:
    pre-build:
      - echo "------------------------------------------------pre-build_start--------------------------------------------"
      - env
      - echo "------------------------------------------------pre-build_end--------------------------------------------
    build:
      - echo "------------------------------------------------build_start--------------------------------------------"
      - env
      - npm install
      - npm run build
      - echo "------------------------------------------------build_end--------------------------------------------"
    post-build:
      - echo "------------------------------------------------post-build_start--------------------------------------------"
      - env
      - echo "------------------------------------------------post-build_end--------------------------------------------
run:
  command: npm start
  network:
    port: 3000
  env:
    - name: MYVAR
    - value: FOO
```
The build process gets called TWICE, once with the proper ENV VARs and the second time without them lol (the `env` command step under the build will verify this), which clobbers the first one or loses it, there goes your proper build, I think what's happening, from the logs at least is that app runner is not plumbing the ENV VARs correctly to all the intermediate containers during the build time

2) and if i don't use a config yaml file, just use the UI, you can't use pre-build, post-build and the ENV VARs that you set in the UI don't get passed any of the `*build` steps
![Screenshot 2023-09-25 at 7 06 03 PM](https://github.com/aws/apprunner-roadmap/assets/1398375/39f48f3f-0be8-47a4-9da2-caf07e6ae9c4)
![Screenshot 2023-09-25 at 7 06 09 PM](https://github.com/aws/apprunner-roadmap/assets/1398375/8aa8854c-47ad-4d46-bd4f-1a6ab9bfc7d9)

![Screenshot 2023-09-25 at 8 05 05 PM](https://github.com/aws/apprunner-roadmap/assets/1398375/dd8a04da-d4b1-4673-ade6-164d9bd5fcb9)

This is my [build script](https://github.com/drschoice/aws-apprunner-demo0/blob/1fd42e6b6765307228eef4c032f7452175d32541/build.js#L1) by the way:
<img width="838" alt="Screenshot 2023-09-25 at 8 06 16 PM" src="https://github.com/aws/apprunner-roadmap/assets/1398375/7cd1398d-8e39-4d7e-bf99-f0cdb0af8b24">

**Comment by jsheld** [comment]
It seems we have a couple of separate issues here which I'm glad to help you work through. First things first - for the first post, can you provide the service arn for us to take a look? For the second comment, multiple start commands are not supported but build commands should be. I'd also like the service arn so we can take a closer look.

**Comment by akhoury** [comment]
> multiple start commands 

I am not using multiple start commands

>  I'd also like the service arn

i deleted it, now when I try to re-create it fails

![Screenshot 2023-09-26 at 9 55 05 AM](https://github.com/aws/apprunner-roadmap/assets/1398375/cddd53bb-12a6-4094-a3de-7c7b6421b8af)

![Screenshot 2023-09-26 at 9 57 02 AM](https://github.com/aws/apprunner-roadmap/assets/1398375/7640988c-7f68-4623-a4a4-ff8aa9511fb4)

arn 
`arn:aws:apprunner:us-east-1:979199114165:service/aws-demo0/228c56f89db445dcbe7d56d39012e2a6`

**Comment by akhoury** [comment]
@jsheld notice how the build command was called twice, the first time with the proper BUILD ENV VARs, the 2nd time without them, look for `MYVAR` in the logs txt file attached, or highlighted in the screenshot as well.

<img width="803" alt="Screenshot 2023-09-26 at 1 10 38 PM" src="https://github.com/aws/apprunner-roadmap/assets/1398375/4d14a333-5441-436d-9cfe-2b857e588700">


[deployment_ca0e8bfdb49243ea9106f77c9fd9581c.txt](https://github.com/aws/apprunner-roadmap/files/12726179/deployment_ca0e8bfdb49243ea9106f77c9fd9581c.txt)

### YAML

```
version: 1.0
runtime: nodejs16
build:
  commands:
    build:
      - echo "------------------------------------------------build_start--------------------------------------------"
      - npm install
      - npm run build 
      - echo "------------------------------------------------build_done--------------------------------------------"
  env:
    - name: MYVAR
      value: FOO
run:
  command: npm run start
  network:
    port: 3000
    env: PORT
  env:
    - name: MYVAR
      value: FOO
```

**Comment by akhoury** [comment]
Ok so, what's happening is

1) pre-build <-- with ENV VARs
2) build <-- with ENV VARs
3) post-build <-- with ENV VARs
4) build <-- **again! why?? and this time without the ENV VARs**

See the logs below for apprunner.yaml 

https://github.com/drschoice/aws-apprunner-demo0/blob/6d501a843f3280a80ee27b2a3c1529e4b2021b49/apprunner.yaml

[deployment_2b6be6b65c9148b59e94adaca324fef2.json.txt](https://github.com/aws/apprunner-roadmap/files/12726442/deployment_2b6be6b65c9148b59e94adaca324fef2.json.txt)

I will leave this sample app running for 1 week, then I will delete it, `arn:aws:apprunner:us-east-1:979199114165:service/aws-demo0/228c56f89db445dcbe7d56d39012e2a6` unless I can just pause and can you still investigate

**Comment by zjkipping** [comment]
This is still an issue I am running into with my project. I am currently getting around it by setting my NodeJS ENV variables before the `build` command that needs them. Is this being worked on at all?

```yml
build:
  commands:
    pre-build:
      - npm install
    build:
      -MY_ENV_VAR='foo' npm run build
  # This doesn't seem to work correctly?
  # https://github.com/aws/apprunner-roadmap/issues/212
  # env:
  #   - name: MY_ENV_VAR
  #     value: 'foo'
```

**Comment by akhoury** [comment]
@zjkipping this is very risky for sensitive secrets, I don't want to add them to my code repo

**Comment by 0xGuybrush** [comment]
I worked around this with:

```yaml
build:
    env:
    - name: FOO
      value: "bar"
  commands:
    pre-build:
      - yarn install
      # other steps
      - env >> .env 
    build:
      - yarn build # Picks up from `.env`
```

Not ideal & not sure about the risk area of having `.env` lying around (though for me also there's no secrets there)
